export const SERVER_REQUEST_START = 'SERVER_REQUEST_START';
export const SERVER_REQUEST_FINISH = 'SERVER_REQUEST_FINISH';

export const LOAD_DATA = 'LOAD_DATA';
export const LOAD_DATA_START = 'LOAD_DATA_START';
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';
export const LOAD_DATA_FAIL = 'LOAD_DATA_FAIL';
